version: "3"
services:
  pgdev:
    container_name: aptabase_pgdev
    restart: always
    image: postgres:15
    volumes:
      - pgdev-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: aptabase_pw
  mailhog:
    container_name: aptabase_mailhog
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  pgdev-data:
