version: "3"
services:
  app:
    build: ../
    ports:
      - "8080:80"
    environment:
      BASE_URL: https://{{ services.api.url }}
      AUTH_SECRET: sTr0NGs3cr3t
      DATABASE_URL: Server=db;Port=5432;User Id=aptabase;Password=aptabase_pw;Database=aptabase

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: aptabase_pw
    ports:
      - 5432
