name: Aptabase CI
on: push

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: aptabase
          POSTGRES_PASSWORD: aptabase_pw
        ports:
          - 5432:5432
      clickhouse:
        image: clickhouse/clickhouse-server:23.3.8.21
        env:
          CLICKHOUSE_USER: aptabase
          CLICKHOUSE_PASSWORD: aptabase_pw
        ports:
          - 8123:8123
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Run Unit Tests
        run: dotnet test
        working-directory: src

      - name: Run Integration Tests
        run: dotnet test
        working-directory: tests

  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker Build
        run: docker build -t prod_build_img .

      # Push to Public Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag prod_build_img $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ghcr.io/aptabase
          REPOSITORY: aptabase
          IMAGE_TAG: main

  deploy-us:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy to Aptabase US
    runs-on: "ubuntu-latest"
    environment: "Aptabase US"
    needs: [build-and-publish]
    steps:
      - name: Configure AWS credentials (US)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::907052285437:role/github-action
          aws-region: us-east-1

      - name: Login to Amazon ECR (US)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Amazon ECR (US)
        run: |
          docker pull ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG
          docker tag ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: 907052285437.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: aptabase
          IMAGE_TAG: main

  deploy-eu:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy to Aptabase EU
    runs-on: "ubuntu-latest"
    environment: "Aptabase EU"
    needs: [build-and-publish]
    steps:
      - name: Configure AWS credentials (EU)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::907052285437:role/github-action
          aws-region: eu-central-1

      - name: Login to Amazon ECR (EU)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Amazon ECR (EU)
        run: |
          docker pull ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG
          docker tag ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: 907052285437.dkr.ecr.eu-central-1.amazonaws.com
          REPOSITORY: aptabase
          IMAGE_TAG: main
