name: Publish Aptabase
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  build-and-publish:
    name: Publish to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          dotnet test

      - name: Docker Build
        run: |
          docker build -t prod_build_img .

      # Push to Public Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag prod_build_img $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ghcr.io/aptabase
          REPOSITORY: aptabase
          IMAGE_TAG: main

  deploy-us:
    name: Deploy to Aptabase US
    runs-on: "ubuntu-latest"
    environment: "Aptabase US"
    needs: build-and-publish
    steps:
      - name: Configure AWS credentials (US)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::907052285437:role/github-action
          aws-region: us-east-1

      - name: Login to Amazon ECR (US)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Amazon ECR (US)
        run: |
          docker pull ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG
          docker tag ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: 907052285437.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: aptabase
          IMAGE_TAG: main

  deploy-eu:
    name: Deploy to Aptabase EU
    runs-on: "ubuntu-latest"
    environment: "Aptabase EU"
    needs: build-and-publish
    steps:
      - name: Configure AWS credentials (EU)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::907052285437:role/github-action
          aws-region: eu-central-1

      - name: Login to Amazon ECR (EU)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Amazon ECR (EU)
        run: |
          docker pull ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG
          docker tag ghcr.io/aptabase/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: 907052285437.dkr.ecr.eu-central-1.amazonaws.com
          REPOSITORY: aptabase
          IMAGE_TAG: main
